export const store = [
  {
    id: "ba",
    label: "bandeja para angioplastia",
    items: [
      { label: "cuba redonda m", quantity: 1 },
      { label: "cuba redonda p", quantity: 1 },
      { label: "pinça backaus", quantity: 1 },
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
    ],
  },
  {
    id: "bpf",
    label: "bandeja para punção profunda",
    items: [
      { label: "porta agulha de hegar", quantity: 1 },
      { label: "tesoura metzembaum curva", quantity: 1 },
      { label: "pinça dissecção dente de rato", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
      { label: "cuba redonda", quantity: 1 },
      { label: "campo fenestrado 100x100", quantity: 1 },
      { label: "campo simples 160x160", quantity: 1 },
    ],
  },
  {
    id: "bpci",
    label: "bandeja para pequena cirurgia infantil",
    items: [
      { label: "afastador farabeuf", quantity: 2 },
      { label: "porta agulha de hegar", quantity: 1 },
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça kelly curva", quantity: 1 },
      { label: "pinça mosquito reta", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 1 },
      { label: "tesoura mtzembaum curva", quantity: 1 },
      { label: "pinça dissecção vascular", quantity: 1 },
      { label: "pinça dissecção romba", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
      { label: "cuba redonda", quantity: 1 },
    ],
  },
  {
    id: "bpca",
    label: "bandeja para pequena cirurgia de adulto",
    items: [
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 3 },
      { label: "porta agulha de hegar", quantity: 1 },
      { label: "tesoura de metzembaum curva", quantity: 1 },
      { label: "pinça dissecção romba", quantity: 1 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "afastador farabeuf", quantity: 1 },
      { label: "pinça de antissepsia", quantity: 1 },
      { label: "cuba redonda", quantity: 1 },
      { label: "campo fenestrado 1x1", quantity: 1 },
      { label: "campo simples 100x100", quantity: 1 },
    ],
  },
  {
    id: "bcih",
    label: "bandeja para cateterismo infantil da hemodinâmica",
    items: [
      { label: "cuba redonda grande", quantity: 1 },
      { label: "cuba redonda média", quantity: 1 },
      { label: "cuba redonda pequena", quantity: 1 },
      { label: "pinça backaus", quantity: 1 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça kelly curva", quantity: 1 },
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
    ],
  },
  {
    id: "bcah",
    label: "bandeja para cateterismo adulto da hemodinâmica",
    items: [
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça backaus", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
      { label: "cuba redonda pequena", quantity: 1 },
      { label: "cuba redonda média", quantity: 1 },
    ],
  },
];
