export const store = [
  {
    name: "cba1",
    label: "caixa básica adulto nº1",
    marker: "vermelho e cinza",
    items: [
      { label: "pinça autostática", quantity: 1 },
      { label: "pinça kelly", quantity: 3 },
      { label: "tesoura grande", quantity: 12 },
      { label: "afastador farabeuf", quantity: 2 },
      { label: "tesoura de potz", quantity: 3 },
      { label: "clamp", quantity: 10 },
    ],
  },
  {
    name: "cbi2",
    label: "caixa básica infantil nº2",
    marker: "amarelo cintilante",
    items: [
      { label: "pinça kelly", quantity: 1 },
      { label: "pinça", quantity: 3 },
      { label: "tesoura grande", quantity: 12 },
      { label: "afastador farabeuf", quantity: 2 },
      { label: "tesoura de potz", quantity: 3 },
      { label: "clamp", quantity: 10 },
      { label: "clamp", quantity: 10 },
      { label: "pinça", quantity: 3 },
      { label: "clamp", quantity: 10 },
      { label: "clamp", quantity: 10 },
      { label: "pinça", quantity: 3 },
      { label: "clamp", quantity: 10 },
      { label: "tesoura grande", quantity: 12 },
      { label: "clamp", quantity: 10 },
      { label: "afastador farabeuf", quantity: 2 },
      { label: "clamp", quantity: 10 },
      { label: "clamp", quantity: 10 },
    ],
  },
];
