// 5207
// 1765
// 9324
// 6810
// 2546
// 7031,

export const store = [
  {
    id: "cba1",
    label: "caixa básica para cirurgia de adultos nº 1",
    marker: "azul e verde cintilante",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "cba2",
    label: "caixa básica para cirurgia de adultos nº 2",
    marker: "verde",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "cba3",
    label: "caixa básica para cirurgia de adultos nº 3",
    marker: "cinza cintilante",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "cba4",
    label: "caixa básica para cirurgia de adultos nº 4",
    marker: "vermelho e amarelo",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "cba5",
    label: "caixa básica para cirurgia de adultos nº 5",
    marker: "coral",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "cba6",
    label: "caixa básica para cirurgia de adultos nº 6",
    marker: "coral cintilante",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "cba7",
    label: "caixa básica para cirurgia de adultos nº 7",
    marker: "azul marinho",
    items: [
      { label: "afastador autostático", quantity: 2 },
      { label: "afastador farabeuf", quantity: 6 },
      { label: "afastador lengenbeck", quantity: 2 },
      { label: "alicate para fio de aço", quantity: 1 },
      { label: "aspirador de cec", quantity: 3 },
      { label: "aspirador neurocirúrgico", quantity: 1 },
      { label: "aspirador tipo yankauer", quantity: 2 },
      { label: "cabo de bisturi nº3 curto", quantity: 1 },
      { label: "cabo de bisturi nº3 longo", quantity: 2 },
      { label: "cabo de bisturi nº4", quantity: 2 },
      { label: "cabo de bisturi nº7", quantity: 1 },
      { label: "passador de fio", quantity: 2 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça para dissecção vascular longa", quantity: 4 },
      { label: "pinça para dissecção vascular média", quantity: 4 },
      { label: "pinça para dissecção vascular pequena", quantity: 1 },
      { label: "ganchos", quantity: 8 },
      { label: "pinça kelly curva", quantity: 20 },
      { label: "pinça kelly reta", quantity: 6 },
      { label: "pinça kocher", quantity: 15 },
      { label: "pinça tipo backaus", quantity: 12 },
      { label: "porta agulha de hegar", quantity: 8 },
      { label: "porta agulha para fio de aço", quantity: 2 },
      { label: "tesoura lister", quantity: 1 },
      { label: "tesoura reta", quantity: 1 },
      { label: "tesoura curva", quantity: 8 },
      { label: "pinça de tubo", quantity: 4 },
      { label: "pinça duval", quantity: 1 },
      { label: "pinça forster", quantity: 1 },
      { label: "pinça mixter longa", quantity: 2 },
      { label: "pinça mixter média", quantity: 2 },
      { label: "pinça rocherster", quantity: 1 },
      { label: "pinça tipo longuete", quantity: 2 },
      { label: "clamp curvo para aneurisma", quantity: 1 },
      { label: "clamp de cooley parcial", quantity: 1 },
      { label: "clamp femural reto", quantity: 2 },
      { label: "clamp para aorta grande", quantity: 1 },
      { label: "clamp para aorta médio", quantity: 1 },
      { label: "clamp para aorta pequeno", quantity: 1 },
      { label: "clamp satinsky grande", quantity: 1 },
      { label: "clamp satinsky médio", quantity: 1 },
      { label: "clamp satinsky pequeno", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 12 },
      { label: "pinça mosquito reta", quantity: 2 },
    ],
  },
  {
    id: "ba",
    label: "bandeja para angioplastia",
    items: [
      { label: "cuba redonda m", quantity: 1 },
      { label: "cuba redonda p", quantity: 1 },
      { label: "pinça backaus", quantity: 1 },
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
    ],
  },
  {
    id: "bpf",
    label: "bandeja para punção profunda",
    items: [
      { label: "porta agulha de hegar", quantity: 1 },
      { label: "tesoura metzembaum curva", quantity: 1 },
      { label: "pinça dissecção dente de rato", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
      { label: "cuba redonda", quantity: 1 },
      { label: "campo fenestrado 100x100", quantity: 1 },
      { label: "campo simples 160x160", quantity: 1 },
    ],
  },
  {
    id: "bpci",
    label: "bandeja para pequena cirurgia infantil",
    items: [
      { label: "afastador farabeuf", quantity: 2 },
      { label: "porta agulha de hegar", quantity: 1 },
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça kelly curva", quantity: 1 },
      { label: "pinça mosquito reta", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 1 },
      { label: "tesoura mtzembaum curva", quantity: 1 },
      { label: "pinça dissecção vascular", quantity: 1 },
      { label: "pinça dissecção romba", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
      { label: "cuba redonda", quantity: 1 },
    ],
  },
  {
    id: "bpca",
    label: "bandeja para pequena cirurgia de adulto",
    items: [
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça mosquito curva", quantity: 3 },
      { label: "porta agulha de hegar", quantity: 1 },
      { label: "tesoura de metzembaum curva", quantity: 1 },
      { label: "pinça dissecção romba", quantity: 1 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "afastador farabeuf", quantity: 1 },
      { label: "pinça de antissepsia", quantity: 1 },
      { label: "cuba redonda", quantity: 1 },
      { label: "campo fenestrado 1x1", quantity: 1 },
      { label: "campo simples 100x100", quantity: 1 },
    ],
  },
  {
    id: "bcih",
    label: "bandeja para cateterismo infantil da hemodinâmica",
    items: [
      { label: "cuba redonda grande", quantity: 1 },
      { label: "cuba redonda média", quantity: 1 },
      { label: "cuba redonda pequena", quantity: 1 },
      { label: "pinça backaus", quantity: 1 },
      { label: "pinça dente de rato", quantity: 1 },
      { label: "pinça kelly curva", quantity: 1 },
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
    ],
  },
  {
    id: "bcah",
    label: "bandeja para cateterismo adulto da hemodinâmica",
    items: [
      { label: "pinça kelly reta", quantity: 1 },
      { label: "pinça backaus", quantity: 1 },
      { label: "pinça para antissepsia", quantity: 1 },
      { label: "cuba redonda pequena", quantity: 1 },
      { label: "cuba redonda média", quantity: 1 },
    ],
  },
];
